/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registropa.frontend;

import Controller.ProfesorController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Profesor;

/**
 *
 * @author Bautista
 */
public class VBuscarProfesor extends javax.swing.JFrame {

    /**
     * Creates new form VBuscarProfesor
     */
    DefaultTableModel tmodel = new DefaultTableModel();
    ProfesorController profesorcontroller;
    List<Profesor> profesoresbuscados;
    VProfesor vprofesor;
    String[] profesor;
    
    public VBuscarProfesor() {
        vprofesor = new VProfesor();
        profesoresbuscados = new ArrayList<Profesor>();
        profesorcontroller = new ProfesorController();
        initComponents();
        modelotabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(580, 360));
        setMinimumSize(new java.awt.Dimension(580, 360));
        setPreferredSize(new java.awt.Dimension(580, 360));
        getContentPane().setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre", "apellido", "ciudad", "departamento", "area", "id" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(36, 30, 70, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 30, 320, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 540, 170);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancelar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 270, 70, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-evidence-filled-50.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 260, 83, 59);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fondo.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(480, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(480, 400));
        jLabel1.setPreferredSize(new java.awt.Dimension(480, 400));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, -6, 810, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        profesorcontroller.setCampo(jComboBox1.getSelectedItem().toString());
        profesorcontroller.setValor(jTextField1.getText());
        datosModeloTabla();
        jTextField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        vprofesor.setVisible(true);
        vprofesor.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VBuscarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VBuscarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VBuscarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VBuscarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VBuscarProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void modelotabla() {
        tmodel.addColumn("Id");
        tmodel.addColumn("Nombre");
        tmodel.addColumn("Apellido");
        tmodel.addColumn("Tipo Ident");
        tmodel.addColumn("Nº Ident");
        jTable1.setModel(tmodel);
    }

    private void datosModeloTabla(){
        try {
            tmodel.setRowCount(0);
            profesoresbuscados = profesorcontroller.buscarPro();
            for (int i = 0; i < profesoresbuscados.size(); i++) {
                profesor = new String[]{String.valueOf(profesoresbuscados.get(i).getId()),
                    profesoresbuscados.get(i).getNombre(),
                    profesoresbuscados.get(i).getApellidos(),
                    profesoresbuscados.get(i).getTipoIdentificacion().name(),
                    String.valueOf(profesoresbuscados.get(i).getIdentificacion()),

                };
                tmodel.addRow(profesor);
            }
        } catch (Exception e) {
        }
    }
    
    
}
