/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registropa.frontend;

import Controller.ProfesorController;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import modelo.Ciudades;
import modelo.Departamentos;
import modelo.Identificacion;
import modelo.Profesor;
import org.hibernate.HibernateException;

/**
 *
 * @author Bautista
 */
public class VCrearPorfesor extends javax.swing.JFrame {

    /**
     * Creates new form VCrearPorfesor
     */
    ProfesorController profesorcontroller;
    VProfesor vprofesor;
    Profesor profesoractualizar;
    int actividad = 0;

    public VCrearPorfesor() {
        profesorcontroller = new ProfesorController();
        initComponents();
        initDepartamentos();
        initCiudades();
        initTipoIden();
        actividad = 1;
    }

    public VCrearPorfesor(Profesor profesoractualizar) {
        profesorcontroller = new ProfesorController();
        this.profesoractualizar = profesoractualizar;
        initComponents();
        initDepartamentos();
        initCiudades();
        initTipoIden();
        actividad = 2;
    }

    public ProfesorController getProfesorcontroller() {
        return profesorcontroller;
    }

    public void setProfesorcontroller(ProfesorController profesorcontroller) {
        this.profesorcontroller = profesorcontroller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(580, 360));
        setMinimumSize(new java.awt.Dimension(580, 360));
        setPreferredSize(new java.awt.Dimension(580, 360));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 20, 41, 14);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 60, 41, 14);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${profesorcontroller.profesornuevo.nombre}"), jTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextField1);
        jTextField1.setBounds(100, 20, 400, 20);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${profesorcontroller.profesornuevo.apellidos}"), jTextField2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextField2);
        jTextField2.setBounds(100, 60, 400, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(20, 100, 56, 20);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${profesorcontroller.profesornuevo.identificacion}"), jTextField3, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextField3);
        jTextField3.setBounds(100, 100, 140, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Horario:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(250, 100, 40, 14);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(300, 100, 200, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(20, 150, 56, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(240, 150, 56, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Area");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(440, 180, 34, 14);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Departamento");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(240, 180, 70, 14);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ciudad");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 180, 33, 14);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(420, 150, 56, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/images.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-770, -440, 1500, 790);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 540, 210);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/aceptar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 240, 81, 57);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refrescar.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 240, 125, 57);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancelar.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 240, 81, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fondo.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(480, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(480, 400));
        jLabel1.setPreferredSize(new java.awt.Dimension(480, 400));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, -6, 640, 400);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if (actividad == 1) {
                profesorcontroller.getProfesornuevo().setDepartamento(Departamentos.valueOf(jComboBox3.getSelectedItem().toString()));
                profesorcontroller.getProfesornuevo().setCiudad(Ciudades.valueOf(jComboBox2.getSelectedItem().toString()));
                profesorcontroller.getProfesornuevo().setTipoIdentificacion(Identificacion.valueOf(jComboBox1.getSelectedItem().toString()));
                profesorcontroller.guardarprofesornuevo();
            }

            if (actividad == 2) {
                profesoractualizar.setNombre(jTextField1.getText());
                profesoractualizar.setApellidos(jTextField2.getText());
                profesoractualizar.setIdentificacion(Integer.parseInt(jTextField3.getText()));
                profesoractualizar.setDepartamento(Departamentos.valueOf(jComboBox3.getSelectedItem().toString()));
                profesoractualizar.setCiudad(Ciudades.valueOf(jComboBox2.getSelectedItem().toString()));
                profesoractualizar.setTipoIdentificacion(Identificacion.valueOf(jComboBox1.getSelectedItem().toString()));
                profesorcontroller.setProfesoractualizar(profesoractualizar);
                profesorcontroller.editar();
            }

        } catch (HibernateException exception) {
            System.out.println("Problem creating session factory");
            exception.printStackTrace();
        }
        Limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        vprofesor = new VProfesor();
        vprofesor.setVisible(true);
        vprofesor.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
        jTextField1.setText(profesoractualizar.getNombre());
        jTextField2.setText(profesoractualizar.getApellidos());
        jTextField3.setText(String.valueOf(profesoractualizar.getIdentificacion()));
        jComboBox2.setSelectedIndex(profesoractualizar.getCiudad().ordinal());
        jComboBox3.setSelectedIndex(profesoractualizar.getDepartamento().ordinal());
        jComboBox1.setSelectedIndex(profesoractualizar.getTipoIdentificacion().ordinal());
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCrearPorfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCrearPorfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCrearPorfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCrearPorfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCrearPorfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void initDepartamentos() {
        ArrayList<String> departamentos = profesorcontroller.enumDepartamentos();
        DefaultComboBoxModel departamentosmodel = new DefaultComboBoxModel(departamentos.toArray());
        jComboBox3.setModel(departamentosmodel);
    }

    private void initCiudades() {
        ArrayList<String> ciudades = profesorcontroller.enumCiudades();
        DefaultComboBoxModel ciudadesmodel = new DefaultComboBoxModel(ciudades.toArray());
        jComboBox2.setModel(ciudadesmodel);
    }

    private void initTipoIden() {
        ArrayList<String> tipoIdentificacion = profesorcontroller.enumIdentificacion();
        DefaultComboBoxModel tipoidenmodel = new DefaultComboBoxModel(tipoIdentificacion.toArray());
        jComboBox1.setModel(tipoidenmodel);
    }

    private void Limpiar() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
    }

}
