/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registropa.frontend;

import Controller.ProfesorController;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Profesor;

/**
 *
 * @author Bautista
 */
public class VProfesor extends javax.swing.JFrame {

    /**
     * Creates new form Vdocente
     */
    DefaultTableModel Tmodelp = new DefaultTableModel();
    List<Profesor> listaProfesores;
    ProfesorController profesorcontroller;
    VCrearPorfesor vcrearprofesor;
    VBuscarProfesor vbuscarprofesor;
    VPrincipalAdmin vprincipal;
    
    public VProfesor() {
        profesorcontroller = new ProfesorController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(480, 460));
        setMinimumSize(new java.awt.Dimension(480, 460));
        setPreferredSize(new java.awt.Dimension(480, 460));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/buscar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 60, 130, 70);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eliminar.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 40, 147, 79);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editar.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(300, 150, 120, 70);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/crear.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(80, 150, 60, 60);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 250, 400, 100);

        jLabel7.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setText("EDITAR");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 220, 90, 20);

        jLabel8.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setText("ELIMINAR");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 120, 100, 20);

        jLabel9.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 204));
        jLabel9.setText("CREAR");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 210, 90, 20);

        jLabel10.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PROFESOR");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(150, 20, 180, 20);

        jLabel11.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 204));
        jLabel11.setText("BUSCAR");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 120, 90, 20);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PP.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(200, 360, 90, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fondo.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(480, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(480, 400));
        jLabel1.setPreferredSize(new java.awt.Dimension(480, 400));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        tablemodel();
        tableopened();
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        int row = jTable1.getSelectedRow();
        int colmun = jTable1.getSelectedColumn();
        profesorcontroller.setKey((int) jTable1.getValueAt(row, colmun));
        profesorcontroller.eliminar();
        profesorcontroller.listaProfesores();
        tableopened();
        }catch(Throwable e){
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        vcrearprofesor = new VCrearPorfesor();
        vcrearprofesor.setVisible(true);
        vcrearprofesor.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
        int row = jTable1.getSelectedRow();
        int column = jTable1.getSelectedColumn();
        profesorcontroller.setKey((int) jTable1.getValueAt(row, column));
        vcrearprofesor = new VCrearPorfesor(profesorcontroller.traerUnProfesor());
        vcrearprofesor.setVisible(true);
        vcrearprofesor.setLocationRelativeTo(null);
        this.dispose();
        }catch(Throwable e){
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        vbuscarprofesor = new VBuscarProfesor();
        vbuscarprofesor.setVisible(true);
        vbuscarprofesor.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        vprincipal = new VPrincipalAdmin();
        vprincipal.setVisible(true);
        vprincipal.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

   public void tablemodel() {
        Tmodelp.addColumn("Id");
        Tmodelp.addColumn("Nombre");
        Tmodelp.addColumn("Apellido");
        Tmodelp.addColumn("Tipo Ident.");
        Tmodelp.addColumn("Nº Ident.");
        Tmodelp.addColumn("Area");
        jTable1.setModel(Tmodelp);
    }

private void tableopened() {
        listaProfesores = profesorcontroller.getTraerProfesores();
        Tmodelp.setRowCount(0);
        listaProfesores.stream().map((profesores) -> new Object[]{profesores.getId(),
            profesores.getNombre(),
            profesores.getApellidos(),
            profesores.getTipoIdentificacion(),
            profesores.getIdentificacion(),
            profesores.getArea()
        }).map((objetos) -> {
            Tmodelp.addRow(objetos);
            return objetos;
        }).forEachOrdered((_item) -> {
            Tmodelp.getDataVector();
        });
    }
}
